name: WOD_Book
description: A Gym data management and community Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fl_chart: ^0.69.0
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  provider: ^6.1.2
  animated_splash_screen: ^1.3.0
  table_calendar: ^3.1.2
  collection: ^1.18.0
  image_picker: ^1.1.2
  path: ^1.8.3
  mime: ^2.0.0
  http_parser: ^4.0.2
  intl: ^0.19.0
  flutter_dotenv: ^5.0.2
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  win32: ^5.7.0
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 900
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
          weight: 100  
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icons/icon.png"
  adaptive_icon_background: "#ffffff"