// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeRFhPer6VbY9TV6vqzuUdY6UL7cm-vlw',
    appId: '1:775175824072:web:067f1841923b38be1a3bfd',
    messagingSenderId: '775175824072',
    projectId: 'gym-app-f0cdb',
    authDomain: 'gym-app-f0cdb.firebaseapp.com',
    storageBucket: 'gym-app-f0cdb.appspot.com',
    measurementId: 'G-DG1M07R0GC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy87kYMyJdMQInSibAHkekOqlvkPCcQlM',
    appId: '1:775175824072:ios:ebd49f12afdaa6671a3bfd',
    messagingSenderId: '775175824072',
    projectId: 'gym-app-f0cdb',
    storageBucket: 'gym-app-f0cdb.appspot.com',
    iosBundleId: 'com.dashboard.flutter.app.flutterDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeRFhPer6VbY9TV6vqzuUdY6UL7cm-vlw',
    appId: '1:775175824072:web:7de2e0bcc47032411a3bfd',
    messagingSenderId: '775175824072',
    projectId: 'gym-app-f0cdb',
    authDomain: 'gym-app-f0cdb.firebaseapp.com',
    storageBucket: 'gym-app-f0cdb.appspot.com',
    measurementId: 'G-QL3V7XFQMW',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy87kYMyJdMQInSibAHkekOqlvkPCcQlM',
    appId: '1:775175824072:ios:ebd49f12afdaa6671a3bfd',
    messagingSenderId: '775175824072',
    projectId: 'gym-app-f0cdb',
    storageBucket: 'gym-app-f0cdb.appspot.com',
    iosBundleId: 'com.dashboard.flutter.app.flutterDashboard',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6eeet7aaJQjfJV0sOKzCykxOCpHujH6g',
    appId: '1:775175824072:android:f871478c4d9a43b11a3bfd',
    messagingSenderId: '775175824072',
    projectId: 'gym-app-f0cdb',
    storageBucket: 'gym-app-f0cdb.appspot.com',
  );

}